recipes.addShaped(<wizardry:unicorn_horn>, 
	[	
		[<wizardry:fairy_dust>,null,null], 
		[null,<wizardry:fairy_dust>,null], 
		[null,null,<wizardry:fairy_dust>]
	]);
recipes.addShapeless(<wizardry:fairy_imbued_apple>, 	
		[<wizardry:fairy_dust>,<minecraft:apple>]
	);
recipes.addShaped(<wizardry:magic_wand>, 
	[	
		[null,null,<wizardry:fairy_dust>], 
		[null,<wizardry:wisdom_stick>,null], 
		[<wizardry:fairy_dust>,null,null]
	]);